version: '3.8'

services:
  jekyll:
    container_name: jekyll
    image: jekyll/jekyll
    working_dir: /home/jekyll
    volumes:
      - .:/home/jekyll
    ports:
      - 4000:4000
    command: jekyll s 